// Generated by site/scenes/contours.mjs. Don't edit by hand; run that instead.
// The contour map's recipe, the same one site/public/site.js traces on the site.

export const contours = {
  /** One tile of the map, in tile units. Waves repeat a whole number of times across it. */
  size: 960,
  /** Contour lines from the lowest point to the highest; every fourth is an index line. */
  levels: 18,
  lo: -1.7487,
  hi: 2.283,
  /** Stroke widths in tile units. */
  lineWidth: 1.3,
  indexWidth: 2.2,
  /** [cycles across the tile in x, in y, strength, phase, speed in radians a second] */
  waves: [[-4,-1,0.09,1.6765,0.0232],[-1,1,0.5548,4.1273,0.0216],[-3,-4,0.0648,0.2381,0.0196],[3,-3,0.0857,3.5076,0.0372],[0,-4,0.0947,1.0077,0.0268],[1,-4,0.09,0.1451,0.0195],[-3,-3,0.0857,1.5862,-0.0243],[-4,2,0.0784,4.9719,-0.0263],[0,1,1,1.7335,-0.017],[4,-2,0.0784,0.6508,0.0417],[2,-2,0.1708,4.9471,-0.0203],[-3,-3,0.0857,6.1871,0.035],[4,-2,0.0784,6.1142,0.0426],[-4,2,0.0784,5.9543,-0.0312],[-3,-2,0.113,5.9977,0.0311],[-3,4,0.0648,4.11,-0.0307],[3,-2,0.113,1.8817,0.0224],[-1,2,0.2546,5.1819,0.0271],[-4,0,0.0947,2.8875,0.031],[2,2,0.1708,1.1416,-0.0364],[2,0,0.3078,3.4487,-0.018],[4,4,0.0526,3.0281,0.0299]] as [number, number, number, number, number][],
};
